  
    
    
    
version: '3'
services:
  spring-app:
    build: .
    ports:
    - "8085:8085"
    depends_on:
    - "database"

  database:
    image: "mysql:5.6"
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
    - MYSQL_DATABASE=webDatabase

volumes:
  logvolume01: {}         
    